### ISSUE TITLE
Discourse built-in feature?

### ISSUE THREAD

**Issue by AlexP11223** [LeoDavidson/discourse-reset-bump#1]
You said in the Readme that it was already possible in Discourse, just less convenient.

But I think it's a bit different. It allows only to set date of the whole topic, and replaces all post dates, not just bump.

**Comment by LeoDavidson** [comment]
It may have changed since the last time I tried the built-in method, but I think if you set the thread to the time the root post *already has* then it will undo any bumping due to editing of the last post in the thread.

It won't change any visible timestamps because you're setting them to all be the same thing they already are (and any replies keep their relative time offsets from the root post's time, which means they also stay the same), but it will (or at least would last time I tried it) remove the hidden "edited on" timestamp which bumps the thread. It's also a huge pain to do that way, which is why this extension was made.

There's also a built-in bump reset option on threads now, but I did not find it as useful as it doesn't let you pick which posts to reset to. If someone replies with useless information, you'd have to delete their post to stop the thread being bumped using the built-in method, while you can just reset back to the date of a previous post using my extension.

**Comment by AlexP11223** [comment]
Yeah, actually I am looking into this extension because sometimes when moving posts to another topic I don't want to bump the topic, but if these posts were older than the last post in the topic then resetting the bump will move the topic too much behind in the topic list (to the date of the last moved post), so I was just looking for a way to reset bump to the latest original post, which seems to be not possible using built-in methods.
